{{- if .Values.s3.secret.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.s3.secret.name }}
type: Opaque
stringData:
  s3.config: |-
{{  .Values.s3.secret.data | indent 6}}
{{- end }}