{{- $otlpEnabled := include "curator-ray.otlp.enabled" . | eq "true" }}
{{- if or (and .Values.metrics.enabled .Values.metrics.extractNVCFSecrets) (and $otlpEnabled .Values.otlp.extractNVCFSecrets) }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: secret-extractor
data:
  extractor.py: |
{{ .Files.Get "files/extractor.py" | indent 4 }}
{{- end }}
